export const AuthTypes = {
  LOGIN_PENDING: "LOGIN_PENDING",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  SIGNUP_PENDING: "SIGNUP_PENDING",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
};
export const DashboardTypes = {
  PROFILE_PENDING: "PROFILE_PENDING",
  PROFILE_FAILED: "PROFILE_FAILED",
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
  EDUCATION_PENDING: "EDUCATION_PENDING",
  EDUCATION_FAILED: "EDUCATION_FAILED",
  EDUCATION_SUCCESS: "EDUCATION_SUCCESS",
  EXPERIENCE_PENDING: "EXPERIENCE_PENDING",
  EXPERIENCE_FAILED: "EXPERIENCE_FAILED",
  EXPERIENCE_SUCCESS: "EXPERIENCE_SUCCESS",
};
export const ActionTypes = {
  EXPERIENCE_DELETED: "EXPERIENCE_DELETED",
  EDUCATION_DELETED: "EDUCATION_DELETED",
  PROFILE_DELETED: "PROFILE_DELETED",
  POST_DELETED: "POST_DELETED",
  POST_LIKE: "POST_LIKE",
  POST_DISLIKE: "POST_DISLIKE",
};
export const PostTypes = {
  POST_SUCCESS: "POST_SUCCESS",
  POST_FAILED: "POST_FAILED",
  POST_ADDLIKE: "POST_ADDLIKE",
  POST_DISLIKE: "POST_DISLIKE",
  POST_DELETE: "POST_DELETE",
};
